name: QIpInfo
description: "A cool app, that will help you find needed people or company!"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_dotenv: ^5.2.1
  flutter_svg_provider: ^1.0.7
  hugeicons: ^0.0.10
  ionicons: ^0.2.2
  provider: ^6.1.4
  rive_animated_icon: ^2.0.3
  share_plus: ^10.1.4
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  simple_fontellico_progress_dialog: ^0.3.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - .env
    - lib/Assets/Images/

  uses-material-design: true
